import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import 'remixicon/fonts/remixicon.css';
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";
import "./globals.css";
import { UserProvider } from "@/context/userContext";
import { EquipmentProvider } from "@/context/equipmentContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <UserProvider>
          <EquipmentProvider>
            {children}
          </EquipmentProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
